---

- hosts: srv02ubuntu
  become: yes
  tasks:
  -  name: Install PHP on Ubuntu
     apt:
        name=php
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        php7.4-fpm systemd
  handlers:
  - name: php7.4-fpm systemd
    systemd:
     name: php7.4-fpm.service
     enabled: no 
     state: stopped

