---

- hosts: srv02ubuntu
  become: yes
  tasks:
  -  name: Install Apache on Ubuntu
     apt:
        name=apache2
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        apache2 systemd
  -  name: Install nginx on Ubuntu
     apt:
        name=nginx
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        nginx systemd
  handlers:
  - name: apache2 systemd
    systemd:
     name: apache2.service
     enabled: no
     state: stopped
  - name: nginx systemd
    systemd:
     name: nginx.service
     enabled: no
     state: stopped

