---

- hosts: all
  become: yes
  tasks:
  -  name: Install zabbix-agent on RedHat Family
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd

  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
      
  -  name: set 'Server=' in config on RedHat
     when:
      ansible_os_family == "RedHat"
     lineinfile:
      path: /etc/zabbix_agentd.conf
      regexp: '^Server='
      line: Server=10.129.0.27

  -  name: set 'ServerActive=' in config on RedHat
     when:
      ansible_os_family == "RedHat"
     lineinfile:
      path: /etc/zabbix_agentd.conf
      regexp: '^ServerActive='
      line: ServerActive=10.129.0.27

  -  name: set 'Server=' in config on RedHat
     when:
      ansible_os_family == "Debian"
     lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server='
      line: Server=10.129.0.27
  -  name: set 'ServerActive=' in config on Ubuntu
     when:
      ansible_os_family == "Debian"
     lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive='
      line: ServerActive=10.129.0.27

  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
